network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      addresses:
        - 192.168.1.200/24
      gateway4: 192.168.1.1
      nameservers:
          search: []
          addresses: [8.8.8.8, 8.8.4.4]